################################################################
##
## Ripped from https://github.com/IgorYbema/HeishaMon/tree/main/Integrations/Home%20Assistant
## Optimised for heatpump with one zone (Z1), no DHW tank/3-way valve.
##
################################################################

# Automations #
###############
automation:
  #Fetches quiet level from status and sets the selector accordingly
  - alias: Set quiet level selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Quiet_Mode_Level"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.heishamon_quietmode
        option: >-
          {%- if trigger.payload == "0" -%}
            Off
          {%- else -%}
            {{ trigger.payload }}
          {%- endif -%}

  #Sets quiet level to the selected value
  - alias: Set quiet level
    trigger:
      platform: state
      entity_id: input_select.heishamon_quietmode
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetQuietMode
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {%- if states('input_select.heishamon_quietmode') == "Off" -%}
            0
          {%- else -%}
            {{ states('input_select.heishamon_quietmode') }}
          {%- endif -%}

  #Fetches powerful level from status and sets the selector accordingly
  - alias: Set powerful level selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Powerful_Mode_Time"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.heishamon_powermode
        option: >-
          {%- if trigger.payload == "0" -%}
            Off
          {%- else -%}
            {{ (trigger.payload | int) * 30 }} min
          {%- endif -%}

  #Sets powerful level to the selected value
  - alias: Set powerful level
    trigger:
      platform: state
      entity_id: input_select.heishamon_powermode
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetPowerfulMode
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {%- if states('input_select.heishamon_powermode') == "Off" -%}
            0
          {%- else -%}
            {{ "%.0f" % ((states('input_select.heishamon_powermode') | replace("min", "") | int) / 30) }}
          {%- endif -%}

  #Fetches heatmode from status and sets the selector accordingly
  - alias: Set heatmode selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Operating_Mode_State"
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.heishamon_heatmode
        option: >-
          {%- if trigger.payload == "0" -%}
            Heat
          {%- if trigger.payload == "1" -%}
            Cool
          {%- endif -%}

  #Sets heatmode to the selected value
  - alias: Set heatmode
    trigger:
      platform: state
      entity_id: input_select.heishamon_heatmode
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetOperationMode
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {%- if states('input_select.heishamon_heatmode') == "Heat" -%}
            0
          {%- if states('input_select.heishamon_heatmode') == "Cool" -%}
            1
          {%- endif -%}

  #Fetches Z1 temperature from status and sets the selector accordingly
  - alias: Set Z1 selector
    trigger:
      platform: mqtt
      topic: "panasonic_heat_pump/main/Z1_Heat_Request_Temp"
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.heishamon_heatshift_z1
        value: >-
          {{ "%.1f" % (trigger.payload | int) }}

  #Sets Z1 temperature to the selected value
  - alias: Set Z1
    trigger:
      platform: state
      entity_id: input_number.heishamon_heatshift_z1
    action:
      service: mqtt.publish
      data_template:
        topic: panasonic_heat_pump/commands/SetZ1HeatRequestTemperature
        retain: false #IMPORTANT! ALWAYS set retain flag false for commands!
        payload_template: >-
          {{ "%.0f" % (states('input_number.heishamon_heatshift_z1') | int) }}

# input_number #
################
input_number:
  heishamon_heatshift_z1:
    name: Set Zone 1 Temperature
    min: 15
    max: 35
    step: 1

# input_select #
################
input_select:
  heishamon_quietmode:
    name: Set Quiet Mode
    options:
      - "Off"
      - "1"
      - "2"
      - "3"

  heishamon_powermode:
    name: Set Powerful Mode
    options:
      - "Off"
      - 30 min
      - 60 min
      - 90 min

  heishamon_heatmode:
    name: Set Heat Mode
    options:
      #- Heat+DHW
      - Cool
      - Heat
      #- DHW

# sensor #
##########
mqtt:
  sensor:
    #TOP0 - Power state
    - name: Aquarea Power State
      state_topic: "panasonic_heat_pump/main/Heatpump_State"
      value_template: >-
        {%- if value == "0" -%}
          Off
        {%- elif value == "1" -%}
          On
        {%- endif -%}

    #TOP1 - Pumpflow
    - name: Aquarea Pump Flow
      state_topic: "panasonic_heat_pump/main/Pump_Flow"
      unit_of_measurement: "L/min"
      state_class: "measurement"

    #TOP4 - Heat mode (Hot water, Heat or Hot water + heat)
    - name: Aquarea Mode
      state_topic: "panasonic_heat_pump/main/Operating_Mode_State"
      value_template: >-
        {%- if value == "0" -%}
          Heat
        {%- elif value == "1" -%}
          Cool
        {%- elif value == "2" -%}
          Auto
        {%- endif -%}

    #TOP5 - Water inlet temp
    - name: Aquarea Inlet Temperature
      state_topic: "panasonic_heat_pump/main/Main_Inlet_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"
      unique_id: Aquarea_Inlet_Temp

    #TOP6 - Water outlet temp
    - name: Aquarea Outlet Temperature
      state_topic: "panasonic_heat_pump/main/Main_Outlet_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"
      unique_id: Aquarea_Outlet_Temperature

    #TOP7 - Water outlet target temp
    - name: Aquarea Outlet Target Temperature
      state_topic: "panasonic_heat_pump/main/Main_Target_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"

    #TOP8 - Compressor frequency
    - name: Aquarea Compressor Frequency
      state_topic: "panasonic_heat_pump/main/Compressor_Freq"
      unit_of_measurement: "Hz"
      state_class: "measurement"
      unique_id: Aquarea_Compressor_Freq

    #TOP11 - Compressor Operating Time
    - name: Aquarea Compressor Operating Hours
      state_topic: "panasonic_heat_pump/main/Operations_Hours"
      unit_of_measurement: "Hours"
      state_class: "measurement"

    #TOP12 - Compressor On/Off cycle number
    - name: Aquarea Compressor Start/Stop Counter
      state_topic: "panasonic_heat_pump/main/Operations_Counter"
      state_class: "measurement"

    #TOP13 - Main scheduler    

    #TOP14 - Outdoor unit ambient temperature
    - name: Aquarea Outdoor Ambient
      state_topic: "panasonic_heat_pump/main/Outside_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"
    
    #TOP15 - Heating power produced
    - name: Aquarea Power Produced
      state_topic: "panasonic_heat_pump/main/Heat_Power_Production"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      force_update: true
      unique_id: Aquarea_Heat_Production

    #TOP16 - Heating power consumed
    - name: Aquarea Power Consumed
      state_topic: "panasonic_heat_pump/main/Heat_Power_Consumption"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      force_update: true
      unique_id: Aquarea_Heat_Consumption

    #TOP17 - Heating powerful mode
    - name: Aquarea Powerful Mode
      state_topic: "panasonic_heat_pump/main/Powerful_Mode_Time"
      unit_of_measurement: "Min"
      value_template: >-
        {{ (value | int) * 30 }}

    #TOP18 - Heating quiet mode
    - name: Aquarea Quiet Mode
      state_topic: "panasonic_heat_pump/main/Quiet_Mode_Level"
      value_template: >-
        {%- if value == "4" -%}
          Scheduled
        {%- elif value == "0" -%}
          Off
        {%- else -%}
          {{ value }}
        {%- endif -%}

    #TOP19 - Holiday Mode
    - name: Aquarea Holiday Mode
      state_topic: "panasonic_heat_pump/main/Holiday_Mode_State"
      value_template: >-
        {%- if value == "0" -%}
          Off
        {%- elif value == "1" -%}
          On
        {%- endif -%}

    #TOP21 - Outside pipe temp
    - name: Aquarea Outdoor Pipe Temperature
      state_topic: "panasonic_heat_pump/main/Outside_Pipe_Temp"
      unit_of_measurement: "°C"

    #TOP26 - Defrost state
    - name: Aquarea Defrost State
      state_topic: "panasonic_heat_pump/main/Defrosting_State"
      value_template: >-
        {%- if value == "0" -%}
          Inactive
        {%- elif value == "1" -%}
          Active
        {%- endif -%}

    #TOP27 - Heatshift Temperature
    - name: Aquarea Heatshift Temperature
      state_topic: "panasonic_heat_pump/main/Z1_Heat_Request_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"
    
    #TOP28 - Coolshift Temperature
    - name: Aquarea Coolshift Temperature
      state_topic: "panasonic_heat_pump/main/Z1_Cool_Request_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"
      
    #TOP33 - Remote Controller thermostat
    - name: Remote Controller thermostat
      state_topic: "panasonic_heat_pump/main/Room_Thermostat_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"
      unique_id: Aquarea_Thermostat_Temp
      
    #TOP38 - Cooling power produced
    - name: Aquarea Cooling Power Produced
      state_topic: "panasonic_heat_pump/main/Cool_Power_Production"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      force_update: true
      unique_id: Aquarea_Cool_Production

    #TOP39 - Cooling power consumed
    - name: Aquarea Cooling Power Consumed
      state_topic: "panasonic_heat_pump/main/Cool_Power_Consumption"
      unit_of_measurement: "W"
      device_class: "power"
      state_class: "measurement"
      force_update: true
      unique_id: Aquarea_Cool_Consumtion
    
    #TOP42 - Z1_Water_Target_Temp
      #Use TOP7 Main instead

    #TOP44 - Last active error
    - name: Aquarea Last Error
      state_topic: "panasonic_heat_pump/main/Error"

    #TOP49 - Main HEX Outlet temp
    - name: Aquarea Main HEX Outlet Temperature
      state_topic: "panasonic_heat_pump/main/Main_Hex_Outlet_Temp"
      unit_of_measurement: "°C"

    #TOP50 - Discharge temp
    - name: Aquarea Discharge Temperature
      state_topic: "panasonic_heat_pump/main/Discharge_Temp"
      unit_of_measurement: "°C"

    #TOP51 - Inside Pipe temp
    - name: Aquarea Inside Pipe Temperature
      state_topic: "panasonic_heat_pump/main/Inside_Pipe_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"

    #TOP52 - Defrost temp
    - name: Aquarea Defrost Temperature
      state_topic: "panasonic_heat_pump/main/Defrost_Temp"
      unit_of_measurement: "°C"

    #TOP53 - Evaporator Air Outlet temp
    - name: Aquarea Eva Outlet Temperature
      state_topic: "panasonic_heat_pump/main/Eva_Outlet_Temp"
      unit_of_measurement: "°C"

    #TOP54 - Bypass Outlet temp
    - name: Aquarea Bypass Outlet Temperature
      state_topic: "panasonic_heat_pump/main/Bypass_Outlet_Temp"
      unit_of_measurement: "°C"
      state_class: "measurement"

    #TOP55 - lpm temp
    - name: Aquarea Ipm Temperature
      state_topic: "panasonic_heat_pump/main/Ipm_Temp"
      unit_of_measurement: "°C"

    #TOP59 - Water electric heater allowed state
    - name: Aquarea Room Heater Enabled
      state_topic: "panasonic_heat_pump/main/Room_Heater_State"
      value_template: >-
        {%- if value == "0" -%}
          Off
        {%- elif value == "1" -%}
          On
        {%- endif -%}

    #TOP60 - Internal heater state
    - name: Aquarea Internal Heater State
      state_topic: "panasonic_heat_pump/main/Internal_Heater_State"
      value_template: >-
        {%- if value == "0" -%}
          Off
        {%- elif value == "1" -%}
          On
        {%- endif -%}

    #TOP62 - Fan1 speed
    - name: Aquarea Fan 1 Speed
      state_topic: "panasonic_heat_pump/main/Fan1_Motor_Speed"
      unit_of_measurement: "R/min"
      state_class: "measurement"

    #TOP64 - High pressure
    - name: Aquarea High pressure
      state_topic: "panasonic_heat_pump/main/High_Pressure"
      unit_of_measurement: "Kgf/cm2"
      state_class: "measurement"

    #TOP65 - Pump speed
    - name: Aquarea Pump Speed
      state_topic: "panasonic_heat_pump/main/Pump_Speed"
      unit_of_measurement: "R/min"
      state_class: "measurement"

    #TOP66 - Low pressure
    - name: Aquarea Low pressure
      state_topic: "panasonic_heat_pump/main/Low_Pressure"
      unit_of_measurement: "Kgf/cm2"
      state_class: "measurement"

    #TOP67 - Compressor Current
    - name: Aquarea Compressor Current
      state_topic: "panasonic_heat_pump/main/Compressor_Current"
      unit_of_measurement: "A"
      state_class: "measurement"

    ##1-Wire - Example, replace with correct sensor ID
    #- name: 1-wire sensor temperature
    #  state_topic: "panasonic_heat_pump/1wire/1234567890abcdef"
    #  unit_of_measurement: '°C'
    #  value_template: '{{value | round(1) }}'

    # The following S0 topics are only available if S0 is enabled.
    #
    #S0 kWh Meter 1 - Assumed to measure the heat pump consumption
    - name: Aquarea Metered Power Consumption
      state_topic: "panasonic_heat_pump/s0/Watt/1"
      unit_of_measurement: "W"
      state_class: "measurement"

    - name: Aquarea Metered Power Consumption Total
      state_topic: "panasonic_heat_pump/s0/WatthourTotal/1"
      unit_of_measurement: "kWh"
      value_template: >-
        {{ (value | int) / 1000}}
      state_class: "measurement"

    #S0 kWh Meter 2 - Assumed to measure the backup heater consumption
    - name: Aquarea Metered Backup Heater Power Consumption
      state_topic: "panasonic_heat_pump/s0/Watt/2"
      unit_of_measurement: "W"
      state_class: "measurement"

    - name: Aquarea Metered Backup Heater Power Consumption Total
      state_topic: "panasonic_heat_pump/s0/WatthourTotal/2"
      unit_of_measurement: "kWh"
      value_template: >-
        {{ (value | int) / 1000}}
      state_class: "measurement"

  # switch #
  ##########
  switch:
    #Turn on/off holiday mode
    - name: Aquarea Holiday Mode
      command_topic: "panasonic_heat_pump/commands/SetHolidayMode"
      state_topic: "panasonic_heat_pump/main/Holiday_Mode_State"
      qos: 0
      payload_on: "1"
      payload_off: "0"
      retain: false

    #Turn on/off heatpump
    - name: Aquarea Main Power
      command_topic: "panasonic_heat_pump/commands/SetHeatpump"
      state_topic: "panasonic_heat_pump/main/Heatpump_State"
      qos: 0
      payload_on: "1"
      payload_off: "0"
      retain: false

sensor:
  #COP Calculations
  - platform: template
    sensors:
      heishamon_cop:
        friendly_name: "Aquarea COP"
        unit_of_measurement: "x"
        value_template: >-
          {%- if states('sensor.aquarea_power_consumed') | float(0) > 0 -%}
            {{ '%0.1f' % ((states('sensor.aquarea_power_produced') | float ) / (states('sensor.aquarea_power_consumed') | float )) }}
          {%- else -%}
            0.0
          {%- endif -%}

        availability_template: >-
          {%- if is_number(states('sensor.aquarea_power_consumed')) and is_number(states('sensor.aquarea_power_produced')) %}
            true
          {%- else %}
            false
          {%- endif %}

  #Calculation Energy consumed (kWh) - Heat
  - platform: integration
    source: sensor.aquarea_power_consumed
    name: Aquarea Heat Power Consumed
    unit_prefix: k
    method: left
