# Modbus SMA solar inverter
modbus:
  - name: modbus_sma
    type: tcp
    host: !secret sma_inverter_ip
    port: 502
    delay: 0
    message_wait_milliseconds: 600
    timeout: 5
    sensors:
      - name: SMA Actual power
        unique_id: fa400021001
        unit_of_measurement: W
        slave: 3
        address: 30775
        input_type: input
        data_type: int32
        min_value: 0
        device_class: power
        state_class: measurement
      - name: SMA Today yield
        unique_id: fa400021002
        unit_of_measurement: Wh
        slave: 3
        address: 30517
        data_type: int64
        min_value: 0
        device_class: energy
        state_class: total_increasing
      - name: SMA Total
        unique_id: fa400021003
        unit_of_measurement: kWh
        slave: 3
        address: 30531
        input_type: input
        data_type: int32
        min_value: 0
        device_class: energy
        state_class: total_increasing
      - name: SMA DC Voltage 1
        unique_id: fa400021004
        unit_of_measurement: V
        slave: 3
        address: 30771
        input_type: input
        scale: 0.01
        precision: 2
        data_type: int32
        min_value: 0
        device_class: voltage
        state_class: measurement
      - name: SMA DC Current 1
        unique_id: fa400021005
        unit_of_measurement: A
        slave: 3
        address: 30769
        input_type: input
        scale: 0.001
        precision: 3
        data_type: int32
        min_value: 0
        device_class: current
        state_class: measurement
      - name: SMA DC Power 1
        unique_id: fa400021006
        unit_of_measurement: W
        slave: 3
        address: 30773
        input_type: input
        data_type: int32
        min_value: 0
        device_class: power
        state_class: measurement
      - name: SMA DC Voltage 2
        unique_id: fa400021007
        unit_of_measurement: V
        slave: 3
        address: 30959
        input_type: input
        scale: 0.01
        precision: 2
        data_type: int32
        min_value: 0
        device_class: voltage
        state_class: measurement
      - name: SMA DC Current 2
        unique_id: fa400021008
        unit_of_measurement: A
        slave: 3
        address: 30957
        input_type: input
        scale: 0.001
        precision: 3
        data_type: int32
        min_value: 0
        device_class: current
        state_class: measurement
      - name: SMA DC Power 2
        unique_id: fa400021009
        unit_of_measurement: W
        slave: 3
        address: 30961
        input_type: input
        data_type: int32
        min_value: 0
        device_class: power
        state_class: measurement
      - name: SMA temperature
        unique_id: fa400021010
        unit_of_measurement: °C
        slave: 3
        address: 30953
        input_type: input
        scale: 0.1
        precision: 1
        data_type: int32
        min_value: 0
        device_class: temperature
        state_class: measurement
#      - name: SMA earthleakage
#        unique_id: fa400021011
#        unit_of_measurement: A
#        slave: 3
#        address: 30225
#        input_type: input
#        count: 2
#        scale: 0.001
#        precision: 3
#        data_type: int32
#        min_value: 0
#        device_class: current
#        state_class: measurement
#        # VEBUS

#SMA power limit
input_number:
  sma_electricity_meter_power_limit_slider:
    name: SMA Power Limit Slider
    initial: 100
    min: 20
    max: 100
    step: 1

automation:
  alias: SMA Power Limit
  id: fa400021013
  description: ''
  trigger:
    - platform: state
      entity_id: input_number.sma_electricity_meter_power_limit_slider
  condition: []
  action:
    - service: modbus.write_register
      data:
        address: 40016
        slave: 3
        value: '{{ states("input_number.sma_electricity_meter_power_limit_slider") }}'
        hub: modbus_sma
  mode: single
